spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device-mgmt
    username: root
    password: Root@123
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
