server:
  servlet:
    context-path: /devicemgmt
spring:
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: org.h2.Driver
    #url: jdbc:mysql://localhost:3306/device_mgmt
    url: jdbc:h2:mem:device_mgmt
    username: root
    password: Root@123
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true  h2:    console:      enabled: true
      path: /h2